### ISSUE TITLE
Needs to be completed

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/sinatra-basics#1]

**Comment by aviflombaum** [comment]
Done.

@AnnJohn can you have someone review this and mark it as done in the spreadsheets and make sure it gets added to Qualifying and Teacher Training tracks.

**Comment by AnnJohn** [comment]
Assigned to @ipc103 for review

(No PR)

Deadline: 9/17/15

**Comment by ipc103** [comment]
made a minor edit - marking done on the spreadsheet

On Wed, Sep 16, 2015 at 5:45 PM, AnnJohn notifications@github.com wrote:

> Assigned to @ipc103 https://github.com/ipc103 for review
> 
> (No PR)
> 
> Deadline: 9/17/15
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/sinatra-basics/issues/1#issuecomment-140903216
> .

## 

```
  Ian Candy
  Pre-College Instructor
```
