### ISSUE TITLE
Multiple controllers and complex.config.ru too advanced

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/sinatra-basics#2]
We should either separate these into a new repo for later reading OR mark these sections of advanced. This is too much for someone new to Sinatra to understand.
@AnnJohn @ipc103

**Comment by AnnJohn** [comment]
@aviflombaum ^^

**Comment by aviflombaum** [comment]
I agree.

It's two readmes, the first part of this one, which covers a single controller wrapped in a class inheriting from Sinatra::Base and mounting with run is: sinatra-simple-controllers

And then the other section should be sinatra-multiple-controllers

**Comment by dfenjves** [comment]
@AnnJohn who is this assigned to?

**Comment by AnnJohn** [comment]
@dfenjves From the issue, I didn't know whether this was just a suggestion or something that actually needed to be done, so it's not assigned to anyone. 

@ipc103 do you have time to work on this?

**Comment by AnnJohn** [comment]
Assigned to @ipc103 

Deadline: 9/24/15
